# Vagrantfile

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.5'

  config.vm.provision "shell", inline: <<~SHELL
    yum install -y openvswitch
    systemctl start openvswitch
    systemctl enable openvswitch
  SHELL

  config.vm.define 'node1' do |node|
    node.vm.hostname = 'node1'
    node.vm.network 'private_network', ip: '192.168.50.11'
  end

  config.vm.define 'node2' do |node|
    node.vm.hostname = 'node2'
    node.vm.network 'private_network', ip: '192.168.50.12'
  end
end
